spring:
  datasource:
    url: jdbc:mysql://mysql:3306/springedumanager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: springedu
    password: springedupass
  jpa:
    show-sql: false
  flyway:
    locations: classpath:db/migration

logging:
  level:
    com.maurocabrera.springedumanager: INFO